# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy NodeJs Backend

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: 'backend/**'
jobs:
  build:
    runs-on: self-hosted
    defaults:
       run:
         working-directory: ./backend
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Stop existing server
    - run: pm2 stop all || true

    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
    - name: Install dependencies
      run: |
        export NODE_OPTIONS="--max_old_space_size=512"
        # Install dependencies with production flag and limited concurrency
        npm ci --prefer-offline --no-audit --production --maxsockets=1
    - name: Start Server
      env:
        RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
        RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
        RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        RDS_PORT: ${{ secrets.RDS_PORT }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
      run: pm2 start ecosystem.config.js

