# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy NodeJs Backend

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: 'backend/**'
jobs:
  build:

    runs-on: self-hosted
    defaults:
       run:
         working-directory: ./backend
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
    - run: npm cache clean --force
    - run: npm ci
    - run: |
        # If .env doesn't exist, create it
        touch .env
        # Save existing env vars
        cp .env .env.backup || true
        # Write new env vars
        echo "${{ secrets.PROD_ENV}}" > .env
        # Restore old env vars, without overwriting new ones
        cat .env.backup >> .env || true
        # Remove duplicates while preserving the last occurrence of each variable
        awk -F '=' '!seen[$1]++' .env > .env.tmp && mv .env.tmp .env
        # Cleanup
        rm -f .env.backup
    - run: pm2 restart server

